// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWweGopCjhs6GtyWzuFvMP_zNqbtRa1Vw',
    appId: '1:121026623130:web:49834ef48c68604bd21123',
    messagingSenderId: '121026623130',
    projectId: 'language-17553',
    authDomain: 'language-17553.firebaseapp.com',
    storageBucket: 'language-17553.firebasestorage.app',
    measurementId: 'G-N5D674BY0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcMNzKQ3I0J3YzcIoKju-Nk7L25Y-LkGI',
    appId: '1:121026623130:android:cf30e9769556e764d21123',
    messagingSenderId: '121026623130',
    projectId: 'language-17553',
    storageBucket: 'language-17553.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUnLzvK33VzJBmNuappcmisTJFSgJC5ow',
    appId: '1:121026623130:ios:e3a5193a89418952d21123',
    messagingSenderId: '121026623130',
    projectId: 'language-17553',
    storageBucket: 'language-17553.firebasestorage.app',
    iosBundleId: 'com.example.language',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUnLzvK33VzJBmNuappcmisTJFSgJC5ow',
    appId: '1:121026623130:ios:e3a5193a89418952d21123',
    messagingSenderId: '121026623130',
    projectId: 'language-17553',
    storageBucket: 'language-17553.firebasestorage.app',
    iosBundleId: 'com.example.language',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWweGopCjhs6GtyWzuFvMP_zNqbtRa1Vw',
    appId: '1:121026623130:web:6cb4927dc9bb172cd21123',
    messagingSenderId: '121026623130',
    projectId: 'language-17553',
    authDomain: 'language-17553.firebaseapp.com',
    storageBucket: 'language-17553.firebasestorage.app',
    measurementId: 'G-8RD5TNDET6',
  );
}
